### ISSUE TITLE
I can't login to the server using ohmega mod

### ISSUE THREAD

**Issue by Zilgyd** [Swackyy/Ohmega#2]
Hi,
-- Server Forge version 1.21-51.0.33
Mods used (only):
-- elytraaccessory-1.0.0+forge-1.21-1.21.1.jar
-- ohmega-1.2.1+forge-1.21-1.21.1.jar

I can't get into my server, try to login and immediately logout, I could find this in the log:

[07:51:14] [Server thread/INFO] [minecraft/MinecraftServer]: Zilgyd joined the game
[07:51:14] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraftforge.network.SimpleChannel.send(Object, net.minecraftforge.network.PacketDistributor$PacketTarget)" because "com.swacky.ohmega.network.ModNetworking.INSTANCE" is null
        Index: 5
        Listeners:
                0: HIGHEST
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@622f5dd6 builtinMobSpawnBlocker(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
                2: HIGH
                3: ASM: net.minecraftforge.common.ForgeInternalHandler@622f5dd6 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
                4: NORMAL
                5: ASM: class com.swacky.ohmega.event.CommonForgeEvents onPlayerJoin(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.network.SimpleChannel.send(Object, net.minecraftforge.network.PacketDistributor$PacketTarget)" because "com.swacky.ohmega.network.ModNetworking.INSTANCE" is null
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.network.ModNetworking.sendTo(ModNetworking.java:53)
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.syncSlot(CommonForgeEvents.java:70)
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.lambda$syncSlots$0(CommonForgeEvents.java:60)
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:136)
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.syncSlots(CommonForgeEvents.java:58)
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.onPlayerJoin(CommonForgeEvents.java:42)
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.__CommonForgeEvents_onPlayerJoin_EntityJoinLevelEvent.invoke(.dynamic)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290)
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:228)
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.event.ForgeEventFactory.onEntityJoinLevel(ForgeEventFactory.java:992)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.addPlayer(ServerLevel.java:893)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.addNewPlayer(ServerLevel.java:885)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:228)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:152)
        at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
        at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8)
        at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:162)
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:866)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170)
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:136)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:849)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:843)
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:145)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:815)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:820)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:706)
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
        at java.base/java.lang.Thread.run(Unknown Source)

[07:51:14] [Server thread/ERROR] [minecraft/ServerConfigurationPacketListenerImpl]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.network.SimpleChannel.send(Object, net.minecraftforge.network.PacketDistributor$PacketTarget)" because "com.swacky.ohmega.network.ModNetworking.INSTANCE" is null
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.network.ModNetworking.sendTo(ModNetworking.java:53) ~[ohmega-1.2.1+forge-1.21-1.21.1.jar!/:1.2.1] {re:classloading}
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.syncSlot(CommonForgeEvents.java:70) ~[ohmega-1.2.1+forge-1.21-1.21.1.jar!/:1.2.1] {re:classloading}
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.lambda$syncSlots$0(CommonForgeEvents.java:60) ~[ohmega-1.2.1+forge-1.21-1.21.1.jar!/:1.2.1] {re:classloading}
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:136) ~[forge-1.21-51.0.33-universal.jar!/:?] {re:classloading}
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.syncSlots(CommonForgeEvents.java:58) ~[ohmega-1.2.1+forge-1.21-1.21.1.jar!/:1.2.1] {re:classloading}
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.CommonForgeEvents.onPlayerJoin(CommonForgeEvents.java:42) ~[ohmega-1.2.1+forge-1.21-1.21.1.jar!/:1.2.1] {re:classloading}
        at TRANSFORMER/ohmega@1.2.1/com.swacky.ohmega.event.__CommonForgeEvents_onPlayerJoin_EntityJoinLevelEvent.invoke(.dynamic) ~[ohmega-1.2.1+forge-1.21-1.21.1.jar!/:1.2.1] {re:classloading,pl:eventbus:B}
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48) ~[eventbus-6.2.8.jar!/:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[eventbus-6.2.8.jar!/:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290) ~[eventbus-6.2.8.jar!/:?] {}
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:228) ~[forge-1.21-51.0.33-universal.jar!/:?] {re:classloading}
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.event.ForgeEventFactory.onEntityJoinLevel(ForgeEventFactory.java:992) ~[forge-1.21-51.0.33-universal.jar!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.addPlayer(ServerLevel.java:893) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.addNewPlayer(ServerLevel.java:885) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:228) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:152) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.TickTask.run(TickTask.java:18) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:162) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:866) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:136) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:849) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:843) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:145) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:815) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:820) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:706) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[forge-1.21-51.0.33-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
        at java.base/java.lang.Thread.run(Unknown Source) [?:?] {}
[07:51:14] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Zilgyd lost connection: Invalid player data
[07:51:14] [Server thread/INFO] [minecraft/MinecraftServer]: Zilgyd left the game

![2024-08-21_01-53-33](https://github.com/user-attachments/assets/8dba136e-3810-419d-98d0-e5c10fd77844)

I hope it is useful, greetings!

**Comment by Swackyy** [comment]
Thanks for the log, it appears that a networking issue is the cause of it, I have found the problem and will release a new version (1.2.2)  soon.

Sorry for any inconveniences!

**Comment by Swackyy** [comment]
I have published the new version with this bug-fix, you can download it here: [CF](https://www.curseforge.com/minecraft/mc-mods/ohmega/files/5649888) or [Modrinth](https://modrinth.com/mod/ohmega/version/yTsSWQVQ)
